---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: vmware_ReconfigVM_HotAddEnabled
    inherits: 
    description: 
  fields:
  - rel2:
      value: "/Integration/VMware/StateMachines/vSphere/ReconfigVM_HotAddEnabled"
