---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: ReconfigVM_ResizeDisk
    inherits: 
    description: 
  fields:
  - Step2:
      value: "/Integration/VMware/vCenter/ReconfigVM_ResizeDisk"
