---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: ReconfigVM_GuestId
    inherits: 
    description: 
  fields:
  - Step2:
      value: "/Integration/VMware/vCenter/ReconfigVM_GuestId"
  - Step3:
      value: "/Integration/VMware/vCenter/Check_ReconfigVM_GuestId"
